// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeniorTicker.Infrastructure.Persistence.Postgres;

#nullable disable

namespace SeniorTicker.Infrastructure.Persistence.Postgres.Migrations
{
    [DbContext(typeof(TickDbContext))]
    partial class TickDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeniorTicker.Infrastructure.Persistence.Postgres.TickEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Exchange")
                        .HasColumnType("smallint")
                        .HasColumnName("exchange");

                    b.Property<DateTimeOffset>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exchange_ts");

                    b.Property<DateTimeOffset>("IngestTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingest_ts");

                    b.Property<decimal>("Price")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Volume")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeTimestamp")
                        .HasDatabaseName("ix_ticks_exchange_ts_brin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ExchangeTimestamp"), "brin");

                    b.HasIndex("Exchange", "Symbol", "ExchangeTimestamp", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_ticks_dedup_key");

                    b.ToTable("ticks", (string)null);

                    b.HasAnnotation("Npgsql:StorageParameter:fillfactor", 100);
                });
#pragma warning restore 612, 618
        }
    }
}
